cat src/main.js > scripts/geoboard.js
cat src/json.js >> scripts/geoboard.js
cat src/Menu.js >> scripts/geoboard.js
cat src/GDoc.js >> scripts/geoboard.js
cat src/geoms/Geom.js >> scripts/geoboard.js
cat src/geoms/GBPoint.js >> scripts/geoboard.js
cat src/geoms/GBLine.js >> scripts/geoboard.js
cat src/geoms/GBCircle.js >> scripts/geoboard.js
cat src/geoms/GBRay.js >> scripts/geoboard.js
cat src/geoms/GBXLine.js >> scripts/geoboard.js
cat src/geoms/GBParaLine.js >> scripts/geoboard.js
cat src/geoms/GBPerpLine.js >> scripts/geoboard.js
cat src/geoms/GBPoO.js >> scripts/geoboard.js
cat src/geoms/GBInters.js >> scripts/geoboard.js
cat src/geoms/GBLocus.js >> scripts/geoboard.js
cat src/geoms/GBMidpoint.js >> scripts/geoboard.js
cat src/command/Command.js >> scripts/geoboard.js
cat src/command/ConstructCircle.js >> scripts/geoboard.js
cat src/command/ConstructIntersection.js >> scripts/geoboard.js
cat src/command/ConstructLine.js >> scripts/geoboard.js
cat src/command/ConstructLocus.js >> scripts/geoboard.js
cat src/command/ConstructMidpoint.js >> scripts/geoboard.js
cat src/command/ConstructParaLine.js >> scripts/geoboard.js
cat src/command/ConstructPerpLine.js >> scripts/geoboard.js
cat src/command/ConstructPoint.js >> scripts/geoboard.js
cat src/command/ConstructPoO.js >> scripts/geoboard.js
cat src/command/Delete.js >> scripts/geoboard.js
cat src/command/Translate.js >> scripts/geoboard.js
cat src/actions/Action.js >> scripts/geoboard.js
cat src/actions/SelectionAction.js >> scripts/geoboard.js
cat src/actions/PointAction.js >> scripts/geoboard.js
cat src/actions/CircleAction.js >> scripts/geoboard.js
cat src/actions/LineAction.js >> scripts/geoboard.js
# java -jar yuicompressor-2.4.6.jar scripts/geoboard.js -o scripts/geoboard.compiled.js
